-- CreateTable
CREATE TABLE "Configuracion" (
    "id" TEXT NOT NULL,
    "nombreSitio" TEXT NOT NULL DEFAULT 'La Bayer Experimental',
    "nombreCorto" TEXT NOT NULL DEFAULT 'La Bayer',
    "descripcion" TEXT,
    "direccion" TEXT NOT NULL DEFAULT 'Av. Juan B. Justo 6050',
    "ciudad" TEXT NOT NULL DEFAULT 'Buenos Aires',
    "provincia" TEXT NOT NULL DEFAULT 'CABA',
    "pais" TEXT NOT NULL DEFAULT 'Argentina',
    "codigoPostal" TEXT,
    "telefono" TEXT,
    "email" TEXT NOT NULL DEFAULT 'hola@labayer.org',
    "whatsapp" TEXT,
    "logoUrl" TEXT,
    "faviconUrl" TEXT,
    "imagenDefault" TEXT,
    "instagram" TEXT,
    "facebook" TEXT,
    "twitter" TEXT,
    "youtube" TEXT,
    "tiktok" TEXT,
    "colorPrimario" TEXT DEFAULT '#000000',
    "colorSecundario" TEXT DEFAULT '#ffffff',
    "terminosUrl" TEXT,
    "privacidadUrl" TEXT,
    "sobreNosotros" TEXT,
    "cbu" TEXT,
    "alias" TEXT,
    "cuit" TEXT,
    "mercadoPagoAccessToken" TEXT,
    "mercadoPagoPublicKey" TEXT,
    "metaTitle" TEXT,
    "metaDescription" TEXT,
    "metaKeywords" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Configuracion_pkey" PRIMARY KEY ("id")
);
